#!/usr/bin/with-contenv bash

# generate fresh crontab
echo "${CRON_SCHEDULE} exec s6-setuidgid abc /usr/bin/offlineimap -o -c /config/offlineimaprc 2>&1" > /tmp/crontabs/root

# run offlineimap synchronization via crontab
/usr/sbin/crond -f -S -c /tmp/crontabs
