#!/bin/bash
set -e  # Exit on error

# environment variables from Docker Cloud build-server
DOCKER_REPO="${DOCKER_REPO}"    # e.g. "index.docker.io/cryptopath/offlineimap"
DOCKER_TAG="${DOCKER_TAG}"      # e.g. "0.1.0" or "master"

# tag image with 'latest'
docker tag ${DOCKER_REPO}:${DOCKER_TAG} ${DOCKER_REPO}:latest

# don't push image if '--no-push' was specified
if [ "$1" != "--no-push" ]; then
  docker push ${DOCKER_REPO}:latest
fi
