#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
  /tmp/crontabs \
  "${CONFIG_PATH}/email" \
  "${SECRETS_PATH}" \
  "${MAIL_PATH}"

# copy default config
[[ ! -f "${CONFIG_PATH}/offlineimaprc" ]] && \
  cp /defaults/offlineimaprc "${CONFIG_PATH}/offlineimaprc"

# set permissions
chown abc:abc \
  "${CONFIG_PATH}" \
  "${CONFIG_PATH}"/{offlineimaprc,email} \
  "${SECRETS_PATH}" \
  "${MAIL_PATH}"
